GROUND_WIDTH = 432
GROUND_HEIGHT = 304
GROUND_HALF_WIDTH = GROUND_WIDTH // 2
HUMAN_DISPLAY_SCALE = 1.0
HUMAN_DISPLAY_WIDTH = int(GROUND_WIDTH * HUMAN_DISPLAY_SCALE)
HUMAN_DISPLAY_HEIGHT = int(GROUND_HEIGHT * HUMAN_DISPLAY_SCALE)

PLAYER_LENGTH = 64
PLAYER_HALF_LENGTH = PLAYER_LENGTH // 2
PLAYER_TOUCHING_GROUND_Y_COORD = 244

BALL_RADIUS = 20
BALL_TOUCHING_GROUND_Y_COORD = 252

NET_PILLAR_HALF_WIDTH = 25
NET_PILLAR_TOP_TOP_Y_COORD = 176
NET_PILLAR_TOP_BOTTOM_Y_COORD = 192
